[package]
name = "blueprint_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
blueprint_core = { path = "../core" }

[dependencies.clap]
version = "4.3.0"
features = ["derive"]

[[bin]]
name = "blueprint"
path = "src/main.rs"