.Dd 6/1/23
.Dt Blueprint
.Os Linux
.Sh NAME
.Nm Blueprint
.Sh SYNOPSIS
.Nm

.Sh DESCRIPTION          \" Section Header - required - don't modify
 Blueprint improves the initial experience developers have when starting to work with a new codebase, project or system. The initial setup and configuration can often be time-consuming and frustrating, leading to delays in productivity and a steep learning curve for newcomers. 
.El                      \" Ends the list
.Pp
.\" .Sh ENVIRONMENT      \" May not be needed
.\" .Bl -tag -width "ENV_VAR_1" -indent \" ENV_VAR_1 is width of the string ENV_VAR_1
.\" .It Ev ENV_VAR_1
.\" Description of ENV_VAR_1
.\" .It Ev ENV_VAR_2
.\" Description of ENV_VAR_2
.\" .El